version: '3.1'

services:

  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
   container_name: elasticsearch
   environment:
     - discovery.type=single-node
   ports:
    - "9200:9200"
   volumes:
    - elasticsearch-data:/opt/elastic7/data
   networks:
    - docker-network

  kibana:
   image: docker.elastic.co/kibana/kibana:7.5.0
   container_name: kibana
   ports:
    - "5601:5601"
   depends_on:
    - elasticsearch
   networks:
    - docker-network

networks:
  docker-network:
    driver: bridge

volumes:
  elasticsearch-data:
